### ISSUE TITLE
New Experience : Submit ANY Experience

### ISSUE THREAD

**Issue by DaytonID** [anyproto/gallery#139]
### Experience

[Anytype_Diary.ver01.zip](https://github.com/user-attachments/files/17089885/Anytype_Diary.ver01.zip)

### Title

Journal & Diary

### Screenshots

![Screenshot1](https://github.com/user-attachments/assets/98f1a661-45df-4156-b5eb-8bcce0996d7f)
![Screenshot2](https://github.com/user-attachments/assets/2bf46052-b97f-44fd-9133-8acf2312938a)
![Screenshot3](https://github.com/user-attachments/assets/a5b0063b-90fa-44a5-af84-a4510edf8e67)
![Screenshot4](https://github.com/user-attachments/assets/b55303f9-2941-44d5-928d-5c78e9a863b1)
![Screenshot5](https://github.com/user-attachments/assets/4c43a349-06b9-4cfe-abe3-05a0d35d04a0)

### Description

This is the interface of a journal planning system. The overall layout is simple and bright, allowing users to easily manage and record their goals, plans, and daily life details.

### Categories

Personal Growth

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by DaytonID** [comment]
I'm not sure where the problem is? How to solve this problem?

**Comment by fuksman** [comment]
Hello @DaytonID, we will address this ourselves. Thank you for contribution!

**Comment by KirillSto** [comment]
Thank you for uploading such a wonderful experience, @DaytonID !
Basically, validation failed due to homepage not being set in space settings. We have fixed that, so now **Journal/Diary(Homepage)** is set as Homepage and it is a first page that will be opened on space openning.

We are going to upgrade our validation tool, so it will provide more utile instructions how to improve particular experience :slightly_smiling_face:
