### ISSUE TITLE
Zen system

### ISSUE THREAD

**Issue by Hexara7777** [anyproto/gallery#18]
### Experience

[Anytype.20231222.164735.4.zip](https://github.com/anyproto/gallery/files/13753885/Anytype.20231222.164735.4.zip)

### Title

Zen System

### Screenshots

![Anytype_w4JrPuG7sM](https://github.com/anyproto/gallery/assets/130001839/09e76f61-8c69-4c68-9440-0d4089a0b1e0)
![Anytype_VSa4gjjUuX](https://github.com/anyproto/gallery/assets/130001839/85c0c858-6cab-4933-8a57-8fd8107598e6)
![Anytype_3yhkvvrRak](https://github.com/anyproto/gallery/assets/130001839/13697419-46be-41f8-83ac-a120cdb11d81)
![Anytype_gqt632qgTj](https://github.com/anyproto/gallery/assets/130001839/54985a0a-d5ff-4cfb-a413-b090dcf4d54f)
![Anytype_selYgxsnle](https://github.com/anyproto/gallery/assets/130001839/0a12c573-0628-49d9-b002-ee1f3248d5db)

### Description

A simple zen system to manage your whole space, partially follows PARA method.
Icons used can be found at https://community.anytype.io/t/zen-system-v0-1/12791

### Categories

Dashboard, Project tracking, Collection

### Language

en-US

### Terms

- [X] I agree that this Experience is licensed under the MIT License.
- [X] I have intellectual property rights and/or permission to contribute the Experience and its content.
- [X] I confirm that the Experience does not contain any harmful or malicious content.

**Comment by fuksman** [comment]
Hello @Hexara7777, thank you for the great submission!
I would recommend that you change the title of the experience to "Zen System." This way, when you submit new versions, they will update the existing experience. Otherwise, v0.1, v0.5, etc. will exist simultaneously.
Additionally, the screenshots have different heights, which will not look good in the gallery. Please make all the screenshots the same size.
You can do this by either editing the existing issue or by closing this issue and creating a new one.

**Comment by Hexara7777** [comment]
Done 😁

**Comment by fuksman** [comment]
@Hexara7777 thank you for being the first contributor to the Gallery!
